[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-zero.json"

#The bootimage runner command is specifically designed to be usable as a runner executable. It links the given executable with the projectâ€™s bootloader dependency and then launches QEMU.
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
